apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product.fullname" . }}
  labels:
    app: {{ include "product.name" . }}
    chart: {{ include "product.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.properties: |-
    spring.datasource.url={{ .Values.spring.datasource.url }}
    spring.datasource.username={{ .Values.spring.datasource.username }}
    spring.datasource.password={{ .Values.spring.datasource.password }}
    # Add more configuration properties as needed

