apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      serviceAccountName: my-service-account  # Reference to the ServiceAccount
      containers:
        - name: product
          image: deepak025/springboot
          ports:
            - containerPort: 8080
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: product
                labels:
                  app: product
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: product
                template:
                  metadata:
                    labels:
                      app: product
                  spec:
                    serviceAccountName: my-service-account  # Reference to the ServiceAccount
                    containers:
                      - name: product
                        image: deepak025/springboot
                        ports:
                          - containerPort: 8080
