apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "deepak2002"  # Set your MySQL root password here
            - name: MYSQL_DATABASE
              value: "ecommerce_db"   # Set your MySQL database name here
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/ecommerce_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "deepak2002"
          ports:
            - containerPort: 3306