replicaCount: 1

image:
  repository: deepak025/springboot
  pullPolicy: IfNotPresent
  tag: latest


service:
  type: ClusterIP

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: deepak2002

rabbitmq:
  host: rabbitmq
  port: 5672
  queue:
    name: department-queue
    durable: true
  exchange:
    name: department-exchange
  binding:
    routingKey: myRoutingKey

mysql:
  rootPassword: "deepak2002"
  database: "ecommerce_db"

ingress:
  enabled: false
  annotations:
  # Add your desired annotations here
  hosts:
    - host: my-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
serviceAccount:
  create: false

autoscaling:
  enabled: false